### ISSUE TITLE
Possible to change the color - for own styling?

### ISSUE THREAD

**Issue by Rainer-Lang** [tittojose/TimeRangePicker#2]

**Comment by tittojose** [comment]
Yes, will surely work on that. Right now there are limitations in custom style for pickers as I have used the built in time picker in android. I can work on custom style for tab colour and header text etc. I would like you to suggests me other attributes too. Thank you.

**Comment by Rainer-Lang** [comment]
The tab indicator should use accent color -> user could see it more easily what tab is activated.

Own style is important for a corporate design of an app. I don't know why Google haven't done this already.......
